import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { User } from '@nx-mean-starter/models';
import { UsersState } from '@nx-mean-starter/state/users';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.scss'],
})
export class UsersComponent implements OnInit {
  users$: Observable<User[]>;
  users = users;

  constructor(private store: Store<UsersState.State>) {}

  ngOnInit() {
    this.users$ = this.store.select(UsersState.getEntitiesArray);
  }

  getUsers() {
    this.store.dispatch(new UsersState.LoadAll());
  }
}

const users = [
  {
    id: 1,
    first_name: 'Averell',
    last_name: 'Giamelli',
    email: 'agiamelli0@timesonline.co.uk',
    gender: 'Male',
    ip_address: '146.125.221.183',
  },
  {
    id: 2,
    first_name: 'Janeen',
    last_name: 'Warnock',
    email: 'jwarnock1@ameblo.jp',
    gender: 'Female',
    ip_address: '52.226.225.90',
  },
  {
    id: 3,
    first_name: 'Sasha',
    last_name: 'Rehor',
    email: 'srehor2@tinypic.com',
    gender: 'Male',
    ip_address: '38.20.10.191',
  },
  {
    id: 4,
    first_name: 'Aharon',
    last_name: 'Stannion',
    email: 'astannion3@amazonaws.com',
    gender: 'Male',
    ip_address: '186.196.55.130',
  },
  {
    id: 5,
    first_name: 'Forester',
    last_name: 'Allott',
    email: 'fallott4@senate.gov',
    gender: 'Male',
    ip_address: '218.124.32.238',
  },
  {
    id: 6,
    first_name: 'Nikolia',
    last_name: 'Gillison',
    email: 'ngillison5@de.vu',
    gender: 'Female',
    ip_address: '80.58.159.114',
  },
  {
    id: 7,
    first_name: 'Jonas',
    last_name: 'Jakubovsky',
    email: 'jjakubovsky6@nsw.gov.au',
    gender: 'Male',
    ip_address: '104.51.212.236',
  },
  {
    id: 8,
    first_name: 'Charlean',
    last_name: 'de Clerq',
    email: 'cdeclerq7@twitpic.com',
    gender: 'Female',
    ip_address: '23.104.204.107',
  },
  {
    id: 9,
    first_name: 'Pammy',
    last_name: 'Jouhan',
    email: 'pjouhan8@cmu.edu',
    gender: 'Female',
    ip_address: '15.206.3.242',
  },
  {
    id: 10,
    first_name: 'Beryle',
    last_name: 'MacKall',
    email: 'bmackall9@google.pl',
    gender: 'Female',
    ip_address: '192.228.37.237',
  },
  {
    id: 11,
    first_name: 'Rudy',
    last_name: 'Murfin',
    email: 'rmurfina@google.nl',
    gender: 'Male',
    ip_address: '5.143.227.239',
  },
  {
    id: 12,
    first_name: 'Finn',
    last_name: 'Akett',
    email: 'fakettb@miibeian.gov.cn',
    gender: 'Male',
    ip_address: '225.124.220.92',
  },
  {
    id: 13,
    first_name: 'Gavra',
    last_name: 'Crayk',
    email: 'gcraykc@indiatimes.com',
    gender: 'Female',
    ip_address: '80.28.187.127',
  },
  {
    id: 14,
    first_name: 'Lavena',
    last_name: 'Bresner',
    email: 'lbresnerd@house.gov',
    gender: 'Female',
    ip_address: '81.159.173.210',
  },
  {
    id: 15,
    first_name: 'Lynnet',
    last_name: 'Hassen',
    email: 'lhassene@dion.ne.jp',
    gender: 'Female',
    ip_address: '38.25.73.242',
  },
  {
    id: 16,
    first_name: 'Josefa',
    last_name: 'Maginn',
    email: 'jmaginnf@topsy.com',
    gender: 'Female',
    ip_address: '104.186.120.145',
  },
  {
    id: 17,
    first_name: 'Kass',
    last_name: 'Weatherup',
    email: 'kweatherupg@harvard.edu',
    gender: 'Female',
    ip_address: '168.75.225.76',
  },
  {
    id: 18,
    first_name: 'Hendrik',
    last_name: 'McNab',
    email: 'hmcnabh@ed.gov',
    gender: 'Male',
    ip_address: '214.105.58.245',
  },
  {
    id: 19,
    first_name: 'Juline',
    last_name: 'Kenningham',
    email: 'jkenninghami@craigslist.org',
    gender: 'Female',
    ip_address: '232.24.254.105',
  },
  {
    id: 20,
    first_name: 'Findlay',
    last_name: 'Edgerly',
    email: 'fedgerlyj@naver.com',
    gender: 'Male',
    ip_address: '236.208.82.207',
  },
  {
    id: 21,
    first_name: 'Noby',
    last_name: 'Livingstone',
    email: 'nlivingstonek@wisc.edu',
    gender: 'Male',
    ip_address: '185.90.247.24',
  },
  {
    id: 22,
    first_name: "D'arcy",
    last_name: 'Sturge',
    email: 'dsturgel@psu.edu',
    gender: 'Male',
    ip_address: '50.30.125.49',
  },
  {
    id: 23,
    first_name: 'Web',
    last_name: 'Kermath',
    email: 'wkermathm@cbc.ca',
    gender: 'Male',
    ip_address: '240.16.118.239',
  },
  {
    id: 24,
    first_name: 'Vaughan',
    last_name: 'Carding',
    email: 'vcardingn@about.me',
    gender: 'Male',
    ip_address: '196.115.63.116',
  },
  {
    id: 25,
    first_name: 'Gregoire',
    last_name: 'Iacovuzzi',
    email: 'giacovuzzio@mapy.cz',
    gender: 'Male',
    ip_address: '35.184.236.82',
  },
  {
    id: 26,
    first_name: 'Kienan',
    last_name: 'Burwood',
    email: 'kburwoodp@harvard.edu',
    gender: 'Male',
    ip_address: '168.115.180.57',
  },
  {
    id: 27,
    first_name: 'Bartholemy',
    last_name: 'Stirzaker',
    email: 'bstirzakerq@bizjournals.com',
    gender: 'Male',
    ip_address: '142.148.128.149',
  },
  {
    id: 28,
    first_name: 'Kerwinn',
    last_name: 'Gillice',
    email: 'kgillicer@multiply.com',
    gender: 'Male',
    ip_address: '88.161.90.22',
  },
  {
    id: 29,
    first_name: 'Patty',
    last_name: 'Gretham',
    email: 'pgrethams@jimdo.com',
    gender: 'Female',
    ip_address: '45.127.32.200',
  },
  {
    id: 30,
    first_name: 'Mahala',
    last_name: 'Tavner',
    email: 'mtavnert@google.nl',
    gender: 'Female',
    ip_address: '160.26.98.204',
  },
  {
    id: 31,
    first_name: 'Perry',
    last_name: 'Pillans',
    email: 'ppillansu@independent.co.uk',
    gender: 'Male',
    ip_address: '59.197.228.253',
  },
  {
    id: 32,
    first_name: 'Dirk',
    last_name: "O'Hoey",
    email: 'dohoeyv@wix.com',
    gender: 'Male',
    ip_address: '77.228.125.34',
  },
  {
    id: 33,
    first_name: 'Dorian',
    last_name: 'Elintune',
    email: 'delintunew@lulu.com',
    gender: 'Male',
    ip_address: '194.202.105.26',
  },
  {
    id: 34,
    first_name: 'Vikki',
    last_name: 'Annetts',
    email: 'vannettsx@ucoz.ru',
    gender: 'Female',
    ip_address: '84.215.36.115',
  },
  {
    id: 35,
    first_name: 'Barron',
    last_name: 'Gilmour',
    email: 'bgilmoury@microsoft.com',
    gender: 'Male',
    ip_address: '253.130.77.115',
  },
  {
    id: 36,
    first_name: 'Debee',
    last_name: 'Repper',
    email: 'drepperz@goodreads.com',
    gender: 'Female',
    ip_address: '39.157.138.54',
  },
  {
    id: 37,
    first_name: 'Pooh',
    last_name: 'Mewhirter',
    email: 'pmewhirter10@theguardian.com',
    gender: 'Male',
    ip_address: '92.227.62.73',
  },
  {
    id: 38,
    first_name: 'Dominga',
    last_name: 'Ughetti',
    email: 'dughetti11@phpbb.com',
    gender: 'Female',
    ip_address: '26.245.81.226',
  },
  {
    id: 39,
    first_name: 'Josiah',
    last_name: 'McQuin',
    email: 'jmcquin12@over-blog.com',
    gender: 'Male',
    ip_address: '130.184.16.32',
  },
  {
    id: 40,
    first_name: 'Tam',
    last_name: 'Dunford',
    email: 'tdunford13@statcounter.com',
    gender: 'Male',
    ip_address: '247.183.129.189',
  },
  {
    id: 41,
    first_name: 'Rogerio',
    last_name: 'Glancey',
    email: 'rglancey14@goo.gl',
    gender: 'Male',
    ip_address: '140.76.245.14',
  },
  {
    id: 42,
    first_name: 'Nicolis',
    last_name: 'Westpfel',
    email: 'nwestpfel15@shinystat.com',
    gender: 'Male',
    ip_address: '134.107.180.241',
  },
  {
    id: 43,
    first_name: 'Hillary',
    last_name: 'Hedney',
    email: 'hhedney16@goodreads.com',
    gender: 'Male',
    ip_address: '93.193.223.42',
  },
  {
    id: 44,
    first_name: 'Sam',
    last_name: 'Platt',
    email: 'splatt17@slate.com',
    gender: 'Male',
    ip_address: '19.57.126.117',
  },
  {
    id: 45,
    first_name: 'Bendick',
    last_name: 'Bools',
    email: 'bbools18@accuweather.com',
    gender: 'Male',
    ip_address: '69.188.205.32',
  },
  {
    id: 46,
    first_name: 'Thibaud',
    last_name: 'Quarterman',
    email: 'tquarterman19@unc.edu',
    gender: 'Male',
    ip_address: '99.140.145.239',
  },
  {
    id: 47,
    first_name: 'Ferdinande',
    last_name: 'Southcomb',
    email: 'fsouthcomb1a@discuz.net',
    gender: 'Female',
    ip_address: '99.180.177.109',
  },
  {
    id: 48,
    first_name: 'Haskel',
    last_name: 'Kenneway',
    email: 'hkenneway1b@stumbleupon.com',
    gender: 'Male',
    ip_address: '141.96.123.208',
  },
  {
    id: 49,
    first_name: 'Graehme',
    last_name: 'Bothbie',
    email: 'gbothbie1c@booking.com',
    gender: 'Male',
    ip_address: '165.42.133.209',
  },
  {
    id: 50,
    first_name: 'Val',
    last_name: 'Pill',
    email: 'vpill1d@statcounter.com',
    gender: 'Male',
    ip_address: '233.221.177.248',
  },
  {
    id: 51,
    first_name: 'Hurlee',
    last_name: 'Lineen',
    email: 'hlineen1e@vinaora.com',
    gender: 'Male',
    ip_address: '222.46.150.139',
  },
  {
    id: 52,
    first_name: 'Sibyl',
    last_name: 'Messenbird',
    email: 'smessenbird1f@cdc.gov',
    gender: 'Male',
    ip_address: '169.86.36.207',
  },
  {
    id: 53,
    first_name: 'Casi',
    last_name: 'Given',
    email: 'cgiven1g@is.gd',
    gender: 'Female',
    ip_address: '55.134.28.255',
  },
  {
    id: 54,
    first_name: 'Kerrin',
    last_name: 'Dubock',
    email: 'kdubock1h@vinaora.com',
    gender: 'Female',
    ip_address: '242.238.40.91',
  },
  {
    id: 55,
    first_name: 'Grenville',
    last_name: 'Kelner',
    email: 'gkelner1i@cnn.com',
    gender: 'Male',
    ip_address: '150.145.57.78',
  },
  {
    id: 56,
    first_name: 'Siusan',
    last_name: 'Forth',
    email: 'sforth1j@narod.ru',
    gender: 'Female',
    ip_address: '154.59.11.251',
  },
  {
    id: 57,
    first_name: 'Leigha',
    last_name: 'Norton',
    email: 'lnorton1k@weibo.com',
    gender: 'Female',
    ip_address: '72.100.158.138',
  },
  {
    id: 58,
    first_name: 'Dur',
    last_name: 'Thames',
    email: 'dthames1l@yellowpages.com',
    gender: 'Male',
    ip_address: '127.132.111.12',
  },
  {
    id: 59,
    first_name: 'Tate',
    last_name: 'Bowmen',
    email: 'tbowmen1m@privacy.gov.au',
    gender: 'Female',
    ip_address: '211.100.235.196',
  },
  {
    id: 60,
    first_name: 'Amelita',
    last_name: 'Sambrook',
    email: 'asambrook1n@naver.com',
    gender: 'Female',
    ip_address: '181.190.93.243',
  },
  {
    id: 61,
    first_name: 'Chantal',
    last_name: 'Cartman',
    email: 'ccartman1o@google.ca',
    gender: 'Female',
    ip_address: '161.78.230.101',
  },
  {
    id: 62,
    first_name: 'Cathrin',
    last_name: 'Duncanson',
    email: 'cduncanson1p@wisc.edu',
    gender: 'Female',
    ip_address: '24.109.240.18',
  },
  {
    id: 63,
    first_name: 'Dall',
    last_name: 'Benning',
    email: 'dbenning1q@patch.com',
    gender: 'Male',
    ip_address: '204.58.60.176',
  },
  {
    id: 64,
    first_name: 'Quent',
    last_name: 'Stallon',
    email: 'qstallon1r@unblog.fr',
    gender: 'Male',
    ip_address: '165.111.204.114',
  },
  {
    id: 65,
    first_name: 'Dex',
    last_name: 'Downey',
    email: 'ddowney1s@people.com.cn',
    gender: 'Male',
    ip_address: '64.78.152.33',
  },
  {
    id: 66,
    first_name: 'Elaina',
    last_name: 'Haffenden',
    email: 'ehaffenden1t@marriott.com',
    gender: 'Female',
    ip_address: '174.102.129.88',
  },
  {
    id: 67,
    first_name: 'Raoul',
    last_name: 'Conquest',
    email: 'rconquest1u@ox.ac.uk',
    gender: 'Male',
    ip_address: '230.23.240.59',
  },
  {
    id: 68,
    first_name: 'Calypso',
    last_name: 'Rickards',
    email: 'crickards1v@icq.com',
    gender: 'Female',
    ip_address: '177.174.60.75',
  },
  {
    id: 69,
    first_name: 'Frazier',
    last_name: 'Hardisty',
    email: 'fhardisty1w@oaic.gov.au',
    gender: 'Male',
    ip_address: '89.176.84.182',
  },
  {
    id: 70,
    first_name: 'Dell',
    last_name: 'Burdikin',
    email: 'dburdikin1x@purevolume.com',
    gender: 'Male',
    ip_address: '4.232.22.146',
  },
  {
    id: 71,
    first_name: 'Dave',
    last_name: 'Bolt',
    email: 'dbolt1y@nifty.com',
    gender: 'Male',
    ip_address: '226.3.38.200',
  },
  {
    id: 72,
    first_name: 'Parnell',
    last_name: 'Wintour',
    email: 'pwintour1z@pagesperso-orange.fr',
    gender: 'Male',
    ip_address: '253.60.211.153',
  },
  {
    id: 73,
    first_name: 'Walther',
    last_name: 'Izchaki',
    email: 'wizchaki20@umich.edu',
    gender: 'Male',
    ip_address: '57.112.241.84',
  },
  {
    id: 74,
    first_name: 'Locke',
    last_name: 'Andryushin',
    email: 'landryushin21@storify.com',
    gender: 'Male',
    ip_address: '237.24.40.204',
  },
  {
    id: 75,
    first_name: 'Bernie',
    last_name: 'Beake',
    email: 'bbeake22@businessinsider.com',
    gender: 'Male',
    ip_address: '89.251.41.67',
  },
  {
    id: 76,
    first_name: 'Haily',
    last_name: 'Toal',
    email: 'htoal23@dailymail.co.uk',
    gender: 'Male',
    ip_address: '44.107.41.96',
  },
  {
    id: 77,
    first_name: 'Emmalee',
    last_name: 'Bennett',
    email: 'ebennett24@ifeng.com',
    gender: 'Female',
    ip_address: '8.195.79.221',
  },
  {
    id: 78,
    first_name: 'Marguerite',
    last_name: 'McKerton',
    email: 'mmckerton25@guardian.co.uk',
    gender: 'Female',
    ip_address: '28.190.211.76',
  },
  {
    id: 79,
    first_name: 'Simon',
    last_name: 'Peschka',
    email: 'speschka26@bandcamp.com',
    gender: 'Male',
    ip_address: '192.190.173.18',
  },
  {
    id: 80,
    first_name: 'Rance',
    last_name: "O'Hartagan",
    email: 'rohartagan27@china.com.cn',
    gender: 'Male',
    ip_address: '220.161.225.80',
  },
  {
    id: 81,
    first_name: 'Giovanni',
    last_name: 'Ovett',
    email: 'govett28@google.de',
    gender: 'Male',
    ip_address: '193.11.76.43',
  },
  {
    id: 82,
    first_name: 'Gerta',
    last_name: 'Goldwater',
    email: 'ggoldwater29@freewebs.com',
    gender: 'Female',
    ip_address: '169.156.120.231',
  },
  {
    id: 83,
    first_name: 'Angil',
    last_name: 'Giannotti',
    email: 'agiannotti2a@infoseek.co.jp',
    gender: 'Female',
    ip_address: '83.154.36.86',
  },
  {
    id: 84,
    first_name: 'Clary',
    last_name: 'Kitcatt',
    email: 'ckitcatt2b@storify.com',
    gender: 'Female',
    ip_address: '103.202.180.250',
  },
  {
    id: 85,
    first_name: 'Tynan',
    last_name: 'Daily',
    email: 'tdaily2c@blogspot.com',
    gender: 'Male',
    ip_address: '63.39.57.165',
  },
  {
    id: 86,
    first_name: 'Lib',
    last_name: 'Borgnol',
    email: 'lborgnol2d@sourceforge.net',
    gender: 'Female',
    ip_address: '31.51.8.182',
  },
  {
    id: 87,
    first_name: 'Renie',
    last_name: 'Stucksbury',
    email: 'rstucksbury2e@chicagotribune.com',
    gender: 'Female',
    ip_address: '72.206.84.172',
  },
  {
    id: 88,
    first_name: 'Dorolice',
    last_name: "L'Episcopi",
    email: 'dlepiscopi2f@squidoo.com',
    gender: 'Female',
    ip_address: '112.57.177.41',
  },
  {
    id: 89,
    first_name: 'Nalani',
    last_name: 'Loyndon',
    email: 'nloyndon2g@topsy.com',
    gender: 'Female',
    ip_address: '108.224.89.153',
  },
  {
    id: 90,
    first_name: 'Andriana',
    last_name: 'Palser',
    email: 'apalser2h@netscape.com',
    gender: 'Female',
    ip_address: '204.130.170.234',
  },
  {
    id: 91,
    first_name: 'Ron',
    last_name: 'McGriele',
    email: 'rmcgriele2i@umich.edu',
    gender: 'Male',
    ip_address: '69.153.94.184',
  },
  {
    id: 92,
    first_name: 'Cal',
    last_name: 'Twinborne',
    email: 'ctwinborne2j@simplemachines.org',
    gender: 'Female',
    ip_address: '162.147.159.118',
  },
  {
    id: 93,
    first_name: 'Rosie',
    last_name: 'Bourbon',
    email: 'rbourbon2k@pinterest.com',
    gender: 'Female',
    ip_address: '40.214.171.51',
  },
  {
    id: 94,
    first_name: 'Kakalina',
    last_name: 'Coats',
    email: 'kcoats2l@free.fr',
    gender: 'Female',
    ip_address: '34.28.228.82',
  },
  {
    id: 95,
    first_name: 'Forest',
    last_name: 'Leece',
    email: 'fleece2m@behance.net',
    gender: 'Male',
    ip_address: '103.143.205.144',
  },
  {
    id: 96,
    first_name: 'Vittoria',
    last_name: 'Anger',
    email: 'vanger2n@discuz.net',
    gender: 'Female',
    ip_address: '3.171.133.36',
  },
  {
    id: 97,
    first_name: 'Zia',
    last_name: 'Barrell',
    email: 'zbarrell2o@accuweather.com',
    gender: 'Female',
    ip_address: '78.108.20.80',
  },
  {
    id: 98,
    first_name: 'Carline',
    last_name: 'Rate',
    email: 'crate2p@people.com.cn',
    gender: 'Female',
    ip_address: '137.107.205.29',
  },
  {
    id: 99,
    first_name: 'Worthington',
    last_name: 'Chillingworth',
    email: 'wchillingworth2q@live.com',
    gender: 'Male',
    ip_address: '129.167.134.229',
  },
  {
    id: 100,
    first_name: 'Marwin',
    last_name: 'Chedgey',
    email: 'mchedgey2r@buzzfeed.com',
    gender: 'Male',
    ip_address: '56.253.10.135',
  },
];
